### ISSUE TITLE
How to use this with Socialite?

### ISSUE THREAD

**Issue by ikmolbo** [derekcodes-io/turnstile-laravel#3]
Hi and thanks for this package. I was wondering how to protect oAuth (Socialite) logins with Turnstile. Can you suggest how to integrate the two using your package?

**Comment by derekcodes-io** [comment]
I imagine it's possible. For example, let's say you have a form with the Turnstile JavaScript triggered. When the user submits the form / button to post to a controller, you'll have to confirm the Turnstile `cf-turnstile-response` before redirecting to the oAuth social site.
